name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./scr
          push: true
          file: ./src/Dockerfile
          tags: |
            guipalm4/fake-shop:latest
            guipalm4/fake-shop:v${{ github.run_number}}
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Auth to AWS
        run: echo "Executing auth to AWS"
      - name: Configure kubectl
        run: echo "Executing configure kubectl"
      - name: Deploy to Kubernetes
        run: echo "Executing deploy to Kubernetes"
